<a href="https://colab.research.google.com/github/Siddhartha127/Pytorch_Learning/blob/main/Pytorch_fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [4]:
!nvidia-smi

Fri Sep 20 19:22:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#Tensors:
Tensors are way to represent data specially
multi demensional data

1- Creating tensors: pytorch tensors are created using orch.tensor()

In [5]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [6]:
# a scalar has no dimenssions hence the output is 0
scalar.ndim
# scalar.item() : to convert it back to regular python integer

0

vector: vector usually has 2 dimensions i.e magnitude and direction

In [9]:
#vector
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [11]:
vec.ndim
vec.shape

torch.Size([2])

MATRIX


In [14]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

Tensors


In [18]:
Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
Tensor.ndim

3

In [21]:
Tensor.shape

torch.Size([1, 3, 3])