<a href="https://colab.research.google.com/github/Siddhartha127/Pytorch_Learning/blob/main/Pytorch_fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
print(torch.__version__)

2.4.1+cu121


In [ ]:
!nvidia-smi

Fri Sep 20 19:22:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#Tensors:
Tensors are way to represent data specially
multi demensional data

1- Creating tensors: pytorch tensors are created using orch.tensor()

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
# a scalar has no dimenssions hence the output is 0
scalar.ndim
# scalar.item() : to convert it back to regular python integer

0

vector: vector usually has 2 dimensions i.e magnitude and direction

In [ ]:
#vector
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [ ]:
vec.ndim
vec.shape

torch.Size([2])

MATRIX


In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

Tensors


In [ ]:
Tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

Random tensors are important because the way many neural network learn is that taey start with tensors full of random numbers and then adjust thost random numbers to better represent data


start with random numberes-> look at data ->update random numbers -> look at data ->update random numbers

In [ ]:
#creating a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1267, 0.6755, 0.9645, 0.1608],
        [0.9031, 0.2065, 0.4251, 0.8267],
        [0.3433, 0.2567, 0.1279, 0.9464]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,width and color channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### **Zeros and Ones**

In [ ]:
# create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensors of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# default data type is float
Ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten= torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_range = torch.arange(start=0,end=1000,step=20)
tensor_range

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [ ]:
# Creating a tensors-like
# you want to replicate the shape of a tensor but do not want to define the shape
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
NOTE: Tensors Datatype is one of the 3 big errors you'll run with PyTorch & deep Learning:


1.   Tensors not right datatype.
2.   Tensors not right shape.
3.    Tensors not on the right device.




In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what is the data type of tensor
                               device=None, #cpu or cuda
                               requires_grad=False)  ## whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#because the default data type is float
float_32_tensor.dtype

torch.float32

In [ ]:
#Float 32 tensor
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
#convert float 32 to float 16
float_32to_16_tensor = float_32_tensor.type(torch.float16)
float_32to_16_tensor.dtype


torch.float16

In [ ]:
x = float_32to_16_tensor * float_32_tensor

In [ ]:
x.dtype


torch.float32

### Getting info from tensors

1.   Tensors not right datatype - to get datatype use tensor.dtype
2.   Tensors not right shape - to get shape use tensor.shape
3.    Tensors not on the right device to get device use tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6775, 0.5797, 0.3100, 0.6094],
        [0.5159, 0.4162, 0.2489, 0.4573],
        [0.6583, 0.0273, 0.0886, 0.3031]])

In [ ]:
#find out details about tensor
print(some_tensor)
print(f"Datatype : {some_tensor.dtype}")
print(f"Shape : {some_tensor.shape}")
print(f"Device : {some_tensor.device}")

tensor([[0.6775, 0.5797, 0.3100, 0.6094],
        [0.5159, 0.4162, 0.2489, 0.4573],
        [0.6583, 0.0273, 0.0886, 0.3031]])
Datatype : torch.float32
Shape : torch.Size([3, 4])
Device : cpu



### Manipulating Tensors(tensor operations)



1.   Addition
2.   Substraction
3.   Multiplication(element wise)
4.   Division
5.   Matrix multiplication



In [ ]:
#create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
start_time = time.time()
torch.matmul(tensor, tensor)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 0.00023651123046875 seconds


In [ ]:

# inner dimensions must match

torch.matmul( torch.rand(3,2) , torch.rand(2,5) ), torch.matmul( torch.rand(3,2) , torch.rand(2,5) ).shape

(tensor([[0.4209, 0.4450, 0.2562, 0.7164, 0.5400],
         [0.2500, 0.2349, 0.0724, 0.4614, 0.4002],
         [0.5611, 0.5784, 0.3014, 0.9731, 0.7598]]),
 torch.Size([3, 5]))

### Transposing a Tensor
To fix a tensor shape issue we can manipulate the shape of one of our tensors using a transpose

A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_A= torch.rand(3,2)
tensor_A

tensor([[0.6583, 0.5062],
        [0.5663, 0.6794],
        [0.6680, 0.5892]])

In [ ]:
tensor_B= torch.rand(3,2)
tensor_B

tensor([[0.2283, 0.0397],
        [0.5094, 0.0593],
        [0.3118, 0.5143]])

In [ ]:
tensor_B.T

tensor([[0.2283, 0.5094, 0.3118],
        [0.0397, 0.0593, 0.5143]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[0.1704, 0.3654, 0.4656],
        [0.1563, 0.3288, 0.5260],
        [0.1759, 0.3752, 0.5113]])

In [ ]:
tens = torch.rand(3,4,5)
tens

tensor([[[0.7514, 0.6448, 0.6636, 0.9525, 0.9267],
         [0.8813, 0.2477, 0.6426, 0.7720, 0.0343],
         [0.7661, 0.1785, 0.8585, 0.1549, 0.4043],
         [0.4381, 0.3071, 0.7944, 0.3508, 0.9028]],

        [[0.3773, 0.0651, 0.7318, 0.0691, 0.7617],
         [0.9641, 0.5608, 0.1599, 0.3073, 0.1616],
         [0.2002, 0.4900, 0.5116, 0.9100, 0.2128],
         [0.5256, 0.2435, 0.1117, 0.7197, 0.4962]],

        [[0.5905, 0.1123, 0.5006, 0.0105, 0.8524],
         [0.3161, 0.4773, 0.8654, 0.7653, 0.0951],
         [0.9043, 0.1975, 0.1592, 0.7789, 0.6345],
         [0.0164, 0.4417, 0.3875, 0.5722, 0.4692]]])

In [ ]:
tens.mT.shape# For multiple dimensional tensors

torch.Size([3, 5, 4])

### Finding the min, max,mean,sum etc(tensor aggregation)

In [16]:
# create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [17]:
#find min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [18]:
#find min
torch.max(x),x.max()

(tensor(91), tensor(91))

In [19]:
x.dtype

torch.int64

In [20]:
# mmean function works with float 32 data type
torch.mean(x.type(torch.float32))

tensor(46.)

In [21]:
x.type(torch.float32).mean()

tensor(46.)

In [22]:
#find sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

### Finding the positional min and max (arg min, argmax)

In [23]:
# position in tensor thst has the minimum value
x.argmin()

tensor(0)

In [25]:
# position in tensor thst has the maximum value
x.argmax()

tensor(9)

### Reshape, stacking, squeezing and unsqueezing tensors








*   Reshaping - reshapes tensor into another defined shape
*   View - return a view of an input tensor of certain shape but keep the same memory of the original tensor (If the values in view are changed, the original tensors value will also be changed, but the shape remains.)
*   Stack - stacking tensors on top of each other or side by side
*   Squeeze - removes all 1 dimension tensors from a tensor
*   Unsqueeze - adds a 1 dimension to a target tensor
*   Permute - Return a view of the input with dimensions permuted(swapped) in a certain way






In [27]:
y= torch.arange(1.,10.)
y,y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [28]:
#add an extra dimension
# 3:04
y_reshaped = y.reshape(1,9)